feat: rewrote sshot (w heho)

diff --git a/home/potato/.local/bin/sshot b/home/potato/.local/bin/sshot
--- a/home/potato/.local/bin/sshot
+++ b/home/potato/.local/bin/sshot
@@ -1,153 +1,155 @@
 #!/usr/bin/bash
+title='sshot'
 
-SAVE_PATH_SS="`xdg-user-dir PICTURES`/sshot"
-TMP_PNG_PATH=/tmp/scrscn.png
-MAIM_FLAGS="--hidecursor --quality 1 -s --bordersize 2 -c 1,1,1,1 $TMP_PNG_PATH"
-# FSWEBCAM_FLAGS="--no-banner $TMP_PNG_PATH"
+cache_path="/tmp/sshot"
+save_path="$HOME/"
+notify=false
+beep=false
+slop=false
+file=false
+clip=false
+decode=false
+ocr=false
+xdg=false
 
-mkdir -p $SAVE_PATH_SS
-mkdir -p `dirname $TMP_PNG_PATH`
-
-sound_beep() {
-  echo -e "\a"
+usage() {
+  echo "Usage: $title [OPTIONS] [FILE_PATH]"
+  echo "Options:"
+  echo "  -h, --help              Display this help message"
+  echo "  -n, --notify            Enable notifications"
+  echo "  -b, --beep              Enable beep"
+  echo "  -s, --slop              Enable slop selection"
+  echo "  -f, --file              Save image into save-path"
+  echo "  -c, --clip              Put image into clipboard"
+  echo "  -d, --decode            Enable barcode & qrcode decoding"
+  echo "  -o, --ocr               Enable optical character recognition"
+  echo "  -x, --xdg               Enable XDG support"
+  echo "  --save-path [PATH]      Set image save path"
 }
 
-# prompt user to take the screenshot
-ss_capture_prompt() {
-  maim $MAIM_FLAGS
-  # beep if screenshot was taken
-  if [ $? -ne 0 ]; then exit 1; fi
-  sound_beep
-}
+# default flags
+if [ $# -eq 0 ]; then
+  file=true
+  xdg=true
+fi
 
-# copy to clipboard
-ss_clip() {
-  cat $TMP_PNG_PATH | xclip -selection clip -t image/png
-  cat $TMP_PNG_PATH | xclip -t image/png
-}
-
-# save image to $SAVE_PATH_SS
-ss_save() {
-  cp $TMP_PNG_PATH "$SAVE_PATH_SS/`date +%s`.png"
-}
-
-# returns any decoded text from the image (barcode, qrcode)
-ss_decode() {
-  echo `zbarimg -q --raw $TMP_PNG_PATH`
-}
-
-# cam_capture() {
-#   fswebcam $FSWEBCAM_FLAGS
-#   # beep if screenshot was taken
-#   if [ $? -ne 0 ]; then exit 1; fi
-#   sound_beep
-# }
-
-
-
-ss_ocr() {
-  echo `tesseract -l eng $TMP_PNG_PATH stdout 2>/dev/null`
-  # echo `tesseract -l ara $TMP_PNG_PATH stdout 2>/dev/null`
-  # echo `tesseract -l rus $TMP_PNG_PATH stdout 2>/dev/null`
-}
-
-clip() {
-  ss_capture_prompt
-  ss_clip
-}
-
-save() {
-  ss_capture_prompt
-  ss_clip
-  ss_save
-}
-
-decode() {
-  ss_capture_prompt
-  res=`ss_decode`
-
-  # check if any decodeding result was found
-  if [ -z "$res" ]; then
-    notify-send "scrscn" "No QR detected"
-    exit 1
-  else
-    notify-send "scrscn" "QR Code decoded:\n\n$res"
-    printf %b "$res" | xclip -selection clip
-  fi
-
-}
-
-ocr() {
-  ss_capture_prompt
-  res=`ss_ocr`
-
-  # check if any ocr result was found
-  if [ -z "$res" ]; then
-    notify-send "scrscn" "No text detected"
-    exit 1
-  else
-    notify-send "scrscn" "Text decoded:\n\n$res"
-    printf %b "$res" | xclip -selection clip
-  fi
-}
-
-
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -h|--help)
+      usage
+      exit 0
+      ;;
+    -n|--notify)
+      notify=true
+      shift
+      ;;
+    -b|--beep)
+      beep=true
+      shift
+      ;;
+    -s|--slop)
+      slop=true
+      shift
+      ;;
+    -f|--file)
+      file=true
+      shift
+      ;;
+    -c|--clip)
+      clip=true
+      shift
+      ;;
+    -d|--decode)
+      decode=true
+      shift
+      ;;
+    -o|--ocr)
+      ocr=true
+      shift
+      ;;
+    -x|--xdg)
+      xdg=true
+      shift
+      ;;
+    --save-path)
+      save_path="$2"
+      shift 2
+      ;;
+    *)
+      echo "Error: Unrecognized option '$1'"
+      usage
+      exit 1
+      ;;
+  esac
+done
 
 dep_check() {
-  cmd=$1
-  opt=${2:-true}
-  msg="Missing dependency '$cmd'"
-
-  type -p "$cmd" &>/dev/null || {
-    notify-send "Scrscn" "$msg"
-    echo "$msg"
-    if $opt ; then exit 2 ; fi
+  dep=$1
+  type -p "$dep" &>/dev/null || {
+    echo "missing dependency '$dep'"
+    return 3
   }
 }
 
-help() {
-	cat <<-EOF
-Usage: scrscn COMMAND [ARGS...]
-
-Commands:
-
-    clip              Take a screenshot and save it into clipboard
-    save              Take a screenshot and save into ~/Pictures/screenshots
-    decode            Take a screenshot and save its decoded content into clipboard (qrcodes and barcodes)
-    ocr               Take a screenshot and save its ocr content into clipboard (english)
-    help              Print this help text.
-EOF
-}
-
-default() {
-  clip
-}
-
-main() {
-  if [ $# -eq 0 ]; then
-    default
-    exit 0
-  fi
-
-  cmd="$1"
-  shift
-
-  case "$cmd" in
-    clip|save|decode|ocr|help)
-      "$cmd" "$@"
-      ;;
-    *)
-      echo "Unknown command $cmd"
-      help
-      exit 2
-  esac
-}
-
-dep_check maim
-dep_check xclip
+# set xdg-user-dir based save_path
 dep_check xdg-user-dir
-dep_check notify-send false
-dep_check zbarimg false
-dep_check tesseract false
+if [ $? -eq 0 ] && $xdg; then
+  save_path="$(xdg-user-dir PICTURES)/sshot"
+fi
 
-main "$@"
+# attempt to take screenshot
+if $slop; then
+  maim --hidecursor --quality 1 --bordersize 1 -c 1,1,1,1 $cache_path -s
+else
+  maim --hidecursor --quality 1 --bordersize 1 -c 1,1,1,1 $cache_path
+fi
+
+# failed to take screenshot
+if [ $? -ne 0 ]; then exit 2; fi
+
+# TODO play gtk audio thingy
+if $beep; then
+  echo -e "\a"
+fi
+
+if $file; then
+  cp $cache_path "$save_path/$(date +%s).png"
+fi
+
+if $clip; then
+  cat $cache_path | xclip -selection clip -t image/png
+  cat $cache_path | xclip -t image/png
+fi
+
+decode_data=
+if $decode; then
+  decode_data=$(zbarimg -q --raw $cache_path 2>/dev/null)
+  # if [ -n "$decode_data" ]; then
+  #   echo "no decode data found"
+  # fi
+  if $clip; then
+    echo $decode_data | xclip -selection clip
+    echo $decode_data | xclip
+  fi
+fi
+
+ocr_data=
+if $ocr; then
+  ocr_data=$(tesseract -l eng $cache_path stdout 2>/dev/null)
+  if [ $? -eq 4 ]; then
+    echo "no ocr data found"
+  fi
+  if $clip; then
+    echo $ocr_data | xclip -selection clip
+    echo $ocr_data | xclip
+  fi
+fi
+
+if $notify; then
+  notify-send "$title" "OCR: $ocr_data\nDEC: $decode_data"
+fi
+
+# STATUS CODES
+# 1 failed to parse args
+# 2 failed to take screenshot
+# 3 missing dependency
